api:
  url: "https://api.hyperliquid.xyz"
  account_address: "0xYourAddress"
  secret_key: "yourSecretKey"

settings:
  poll_interval: 60
  log_file: "bot.log"

webhooks:
  discord: "https://discord.com/api/webhooks/XXXX/XXXX"
  slack: "https://hooks.slack.com/services/T0000/B0000/XXXX"

positions:
  - asset: "BTC"
    side: "long"
    entry_price: 50000
    rule: "macd_cross_below_minus40"
  - asset: "ETH"
    side: "short"
    entry_price: 3000
    rule: "rsi_above_70"
